stages:
  data_ingestion:
    cmd: python src\gemstone\pipeline\st_01_data_ingestion.py
    deps:
      - src\gemstone\pipeline\st_01_data_ingestion.py
      - config\config.yaml
    outs:
      - artifacts\data_ingestion\gemstone
    

  data_validation:
    cmd: python src\gemstone\pipeline\st_02_data_validation.py
    deps:
      - src\gemstone\pipeline\st_02_data_validation.py
      - config\config.yaml
    outs:
      - artifacts\data_validation
    

  data_transformation:
    cmd: python src\gemstone\pipeline\st_03_data_transformation.py
    deps:
      - src\gemstone\pipeline\st_03_data_transformation.py
      - config\config.yaml
    outs:
      - artifacts\data_transformation\preprocessing_obj.pkl
      - artifacts\data_transformation\test.csv
      - artifacts\data_transformation\train.csv
    

  model_trainer:
    cmd: python src\gemstone\pipeline\st_04_model_trainer.py
    deps:
      - src\gemstone\pipeline\st_04_model_trainer.py
      - config\config.yaml
    outs:
      - artifacts\model_trainer\model.pkl
    

  model_evaluation:
    cmd: python src\gemstone\pipeline\st_05_model_evaluation.py
    deps:
      - src\gemstone\pipeline\st_05_model_evaluation.py
      - config\config.yaml
      - artifacts\data_transformation\test.csv
      - artifacts\model_trainer\model.pkl
    params:
      - iterations
      - depth
      - learning_rate
      - l2_leaf_reg
    
